spring.application.name=filler

# Configuración de la Base de Datos en Memoria (H2)
spring.datasource.url=jdbc:h2:mem:tinderotakudb;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# Habilitar la consola web de H2 para ver las tablas
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuración de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true